brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
# 核心：强制指定宿主机能访问的 IP
brokerIP1 = host.docker.internal
autoCreateTopicEnable = true